#!/bin/bash
#SBATCH --job-name=ewas     # job name in the queue
#SBATCH --time=01:00:00     # wall time
#SBATCH --ntasks=1          # number of tasks (e.g. MPI processes)
#SBATCH --cpus-per-task=1   # number of threads per task (e.g. OpenMP)
#SBATCH --mem=8G            # amount of memory to request

# load singularity module
module load Singularity

# set up port forwarding between node that submitted job to compute node it is running on
port=8083
echo "EWAS will be started on $(hostname) and port forwarding established from $SLURM_SUBMIT_HOST on port $port"
ssh -N -R ${port}:localhost:${port} $SLURM_SUBMIT_HOST &

# set up environment
if [ -f .env ]
then
  export $(cat .env | xargs)
fi

# make sure temp dir exists
mkdir -p temp

# run the container
singularity run --writable-tmpfs -B ${PWD}/temp:/var/run/apache2/  ewas.img
