#!/bin/bash
if [ -f .env ]
then
  export $(cat .env | xargs)
fi

if [ -f ~/ewas_config ]
then
  export $(cat ~/ewas_config | xargs)
fi

docker run -p 8083:8083 --mount type=bind,source=$EWAS_OUT,target=/app/out \
						--mount type=bind,source=$EWAS_UPLOADS,target=/mnt/data/uploads \
						--mount type=bind,source=$EWAS_RESULTS,target=/app/results ewas1 \
						-o  ${EWAS_OUT} -u ${EWAS_UPLOADS} -r ${EWAS_RESULTS} -t ${EWAS_ROOT} \
						-f ${EWAS_EMAIL_FROM}  -h ${EWAS_EMAIL_HOST} \
						-p ${EWAS_EMAIL_PORT} -s ${EWAS_EMAIL_USER} -w ${EWAS_EMAIL_PASSWORD} $@
